### ISSUE TITLE
Don't echo invalid command responses for single + commands outside of #bot-cmd

### ISSUE THREAD

**Issue by ilocereal** [AberrantFox/hotbot#100]
### Don't echo invalid command responses for single + commands 
When mods make typos with macros, hotbot still replies with the name of the macro that people were trying to invoke after deleting the original message. That can be a little annoying/embarrassing when it's a mod trying to semi-anonymously push someone in the right direction.

**Priority:**
1

**Suggested solution:**
An if statement could be added to the section where commands are handled that checks whether the command is a single + or not before sending a failed command response.

**Comment by AberrantFox** [comment]
Fixed as of 4270062f056336bebf88cd3a0bca5de30a89c7c7
