### ISSUE TITLE
If a command title includes the bot name, don't invoke 

### ISSUE THREAD

**Issue by caffeinewriter** [AberrantFox/hotbot#103]
### <Issue title>

**Priority:**
1

**Suggested solution:**
If a command is invoked, and `MentionListener` is invoked, check to see if the message starts with the command prefix. If it does, ignore the mention.

**Comment by AberrantFox** [comment]
There is a permission for this called "commandMention" which is quite explicit in its existence. I can be quite defensive about mention filtering, but all it takes is one @ everyone to slip through.
