### ISSUE TITLE
Fix the UserID argument.

### ISSUE THREAD

**Issue by fishysnake** [AberrantFox/hotbot#15]
At the moment, this pulls from the cache. It is probably preferable to keep the argument in existence and make it so that it'll poll the JDA looking up the ID to validate it and then, if it is valid, queue the command execution or else fail normally.

This is bothersome because of the nature of how validation is separated from the rest of the code, though quite doable.

**Comment by AberrantFox** [comment]
Fixed as of https://github.com/AberrantFox/hotbot/commit/de865d50cf75e6a9c17d86a4d017d6d0b2c0c781
