### ISSUE TITLE
Allow at-mentions as well as User IDs for commands.

### ISSUE THREAD

**Issue by fishysnake** [AberrantFox/hotbot#18]
Current syntax for commands requires User IDs, e.g.,
`++history 123456789987654321`

Instead, allow at-mentions as well, e.g.,
`++history @targetuser`

**Comment by AberrantFox** [comment]
Closed by https://github.com/AberrantFox/hotbot/commit/1cfe354aec47b0305fdf702de58fc766dbdee129
