### ISSUE TITLE
Suggestion: a command to mute emojis, both global and per user

### ISSUE THREAD

**Issue by GeorgeWL** [AberrantFox/hotbot#2]
I think a mod and higher command to mute emojis when folks are being spammy might be useful.

something like `$emojimute x y`

 X=time Y=optional username, defaults to all of non-mod and lower.

could stop the occasional emoji spam. Not sure if it's worth adding or not though tbh.

I'd try and PR if I knew Java/Kotlin.

**Comment by AberrantFox** [comment]
Not a bad idea, I can make it. Maybe I can make it only for specifically guests or rankless people.

**Comment by AberrantFox** [comment]
Closing this, as Gaius handles emoji spam internally.
