### ISSUE TITLE
Add a remindme command

### ISSUE THREAD

**Issue by fishysnake** [AberrantFox/hotbot#33]

**Comment by AberrantFox** [comment]
Command syntax:

remind <id> <time> <thing>

e.g. ++remind 3232352323 1d0h10m Hi
       ++remindme 2h hello there
       ++remindme repeat-6h bump things!

**Comment by AberrantFox** [comment]
Closed as of https://github.com/AberrantFox/hotbot/commit/6db042e5c718fc6b3175ce9bb0d3fce8bcad59fa
