### ISSUE TITLE
Auto-mute people who mention too many people in their message

### ISSUE THREAD

**Issue by vallode** [AberrantFox/hotbot#50]
### Auto-mute a person when they mention users too much

**Priority:**
1

**Suggested solution:**
~~If hotbot detects a message has more than 3 mentions, mute the person as a way to interrupt further mention spam.~~ We had a person use what seemed to be a self-bot to mention 50 people at a time, this could have been somewhat mitigated if hotbot caught them out instantly.

Further discussion has made it clear that a flat cap wouldn't work, instead introduce a timed cap on mentions for users. If a user makes more than 7 mentions a message mute them or if they make more than 6 mentions in 5 minutes mute them.

**Comment by AberrantFox** [comment]
Closed by https://github.com/AberrantFox/hotbot/commit/e4595445b4022a48bc748c1e92bf9f33a70c29db - will implement the mentionOverTimeListener in 5.1.0
