### ISSUE TITLE
Create an event listener for channel deletes to nuke resources for the sake of storage. 

### ISSUE THREAD

**Issue by AberrantFox** [AberrantFox/hotbot#56]
### ResourceCleanUpListener

**Priority:**
1

**Suggested solution:**
When a channel is deleted, all associated resources should also be deleted, and logged into a logger channel (warning or info seem reasonable) in order to not have dead rows in the database.

**Comment by joshthewall** [comment]
Closed by #115 - merged in 6ab3309d7009f3443838fd10157e9120c086346f
