### ISSUE TITLE
Hotbot crashes on first launch due to missing config dir.

### ISSUE THREAD

**Issue by nglade** [AberrantFox/hotbot#92]
### Hotbot crashes on first launch due to missing config dir.

**Priority:**
2

**Suggested solution:**
Either update the setup instructions (user should create _config_ before launching the bot), or create it automatically.

**Stack Trace.**
```
Exception in thread "main" java.io.FileNotFoundException: config\config.json 
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at me.aberrantfox.hotbot.services.ConfigurationKt.loadConfig(Configuration.kt:65)
        at me.aberrantfox.hotbot.MainAppKt.main(MainApp.kt:30)
```

**Comment by joshthewall** [comment]
The config directory is part of the repo, so you shouldn't have had to create it. I also cloned your fork to make sure and it ran as expected: printing `Starting to load hotbot.` then stopping for the first run, generating `config.json` in `config/`.

**Comment by nglade** [comment]
It works for me, if you execute `java -jar target/hotbot-5.0.9-jar-with-dependencies.jar`  (ie. when the working directory is the repository root), but executing it in a different working directory (for instance when cd'ing into target/ as the manual says), then it crashes.

**Comment by AberrantFox** [comment]
Hi there glade, sorry about that, the instructions are likely quite out of date, since a lot of the work has been going into refactoring and getting more features into the bot. I'll leave this marked as an enhancement to update the installation docs to be more clear and provide screenshots.

**Comment by AberrantFox** [comment]
Just thinking about this, the execution of the jar from outside the directory works because it expects the config directory to be in the directory you execute from @nglade Only thought of that now. :)

**Comment by AberrantFox** [comment]
I'll be fixing this by adding docker later on with a user manual, closing discuss on the manual thread if you need to further
